### ISSUE TITLE
No Internet Connection Issue

### ISSUE THREAD

**Issue by kev8800** [paytabscom/paytabs-ios-library-sample#1]
every time I clicked on the pay button I am having only one message "Internet is not accessible, please check your internet!", I have changed to merchant email and, merchant key

**Comment by ChanakyaHirpara** [comment]
![Screenshot 2019-10-01 at 11 45 56 AM](https://user-images.githubusercontent.com/16621205/65938619-0d615300-e441-11e9-94ca-0c5d56f39f14.png)
Please add this to your plist file.

**Comment by gardencoder** [comment]
Please check https://dev.paytabs.com/docs/ios/
