### ISSUE TITLE
'title' post variable not found

### ISSUE THREAD

**Issue by aparandiy** [paytabscom/paytabs-ios-library-sample#11]
when i tap "PAY NOW" button library returns me an error "'title' post variable not found" without any error code and description, all details are hidden by the library, i use the last iOS version ios_sdk-v4.0.4-ocr
![Simulator Screen Shot - iPhone 8 - 2020-01-24 at 20 36 06](https://user-images.githubusercontent.com/20416958/73099572-6d9a6a00-3ef4-11ea-928b-05c7a7285790.png)

**Comment by paytabscom** [comment]
Hi @aparandiy , please make sure you are passing the following 
  andWithCustomerTitle: "PayTabs Sample App"

**Comment by aparandiy** [comment]
yes, 100% i am passing it, because all init fields are required, so if i can see your payments screen - it means the PTFWInitialSetupViewController was created successfully, i even can't to create a PTFWInitialSetupViewController if i ignore some of init field, all fields are required, i  even tried your test projects in swift and objective-c(from current repo) with our andWithMerchantEmail, andWithMerchantSecretKey, but even there i faced the same issue, i checked all available versions and everyone returns me an error when i tap "PAY NOW" button

**Comment by aparandiy** [comment]
![Знімок екрана  о 19 21 56](https://user-images.githubusercontent.com/20416958/73288339-78f6d980-4203-11ea-8eb4-fc486cbfcd89.png)

**Comment by paytabscom** [comment]
Can you please provide us with the merchant ID you are using?

**Comment by paytabscom** [comment]
Dear @aparandiy, we have investigated the issue and it was due to some missing configuration for your merchant id, the issue is now resolved, kindly try again and let us know if everything is working fine.

**Comment by aparandiy** [comment]
thanks for the efforts, now it works
