### ISSUE TITLE
Why are shipping and billing fields required?

### ISSUE THREAD

**Issue by aparandiy** [paytabscom/paytabs-ios-library-sample#12]
![Знімок екрана  о 11 23 36](https://user-images.githubusercontent.com/20416958/73163080-e1f12b00-40f7-11ea-81bf-1ba5244bde35.png)
i use the latest version ios_sdk-v4.0.4-ocr and swift 5, when i create an object of PTFWInitialSetupViewController i use init method, but this init has all required fields, this fields(billing and shipping details) should be optional and not required, please check it

**Comment by paytabscom** [comment]
Hi @aparandiy , we require billing details for all our transactions, its necessary that the billing details are match that registered on the card, in order for the transaction to be processed successfully and not get rejected by our fraud monitoring tools. If you are providing any services that don't require shipping details, you can pass shipping details same as billing details
