### ISSUE TITLE
Date and Year Picker not showing.

### ISSUE THREAD

**Issue by ShakhawatAi** [paytabscom/paytabs-ios-library-sample#14]
Hello, I'm trying to implement PayTabs in my new project. Pay tabs viewcontroller is loading fine But if I tap on card Date or Year DatePicker not showing.  No Issue with keyboard. Just the date pickers.
![pay](https://user-images.githubusercontent.com/58216252/74310439-71086f00-4d97-11ea-841b-f0a8305cc787.jpg)

**Comment by cogtea** [comment]
@ShakhawatAi can you please archive and send the sample has this error?

**Comment by ShakhawatAi** [comment]
Yeah, why not. Here it is: https://drive.google.com/file/d/1c-MXFJeR8vN-8GyzNqY4PpFe8P7EWKuX/view?usp=sharing

May be it's causing for iOS 13. Take a look.

**Comment by cogtea** [comment]
@ShakhawatAi We did a change to **paytabs-iOS.framework** to fix this issue, please replace 
[paytabs-iOS.framework.zip](https://github.com/paytabscom/paytabs-ios-library-sample/files/4197068/paytabs-iOS.framework.zip), also you have to add new Pod dependency

```pod
  pod 'ActionSheetPicker-3.0'
```

Please try and let us know if it is working fine

**Comment by cogtea** [comment]
@ShakhawatAi for OCR Version, please use the following 
[paytabs-iOS.framework.zip](https://github.com/paytabscom/paytabs-ios-library-sample/files/4197154/paytabs-iOS.framework.zip)

**Comment by ShakhawatAi** [comment]
Yeah it did work. Thanks for your support..

**Comment by cogtea** [comment]
@ShakhawatAi Thanks for your update.
