### ISSUE TITLE
new version 4.0.7 issue: Undefined symbol:OBJC_CLASS_$_PTFwhinitialSetupviewController

### ISSUE THREAD

**Issue by yasirbright** [paytabscom/paytabs-ios-library-sample#15]
When we build we are getting error 
"Undefined symbol:OBJC_CLASS_$_PTFwhinitialSetupviewController"

![issue-1](https://user-images.githubusercontent.com/61177740/74708388-b9aba680-5235-11ea-9e9d-aae0946c5e14.jpg)

**Comment by cogtea** [comment]
@yasirbright Can you please share sample with same issue?

**Comment by cogtea** [comment]
Please use the latest version `4.0.8` https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk
