### ISSUE TITLE
Please remove  AFNetworking pod dependency because it has UIWebview Control, so apple will no accept app with UIwebview

### ISSUE THREAD

**Issue by DangarOpenxcell** [paytabscom/paytabs-ios-library-sample#16]
Please remove AFNetworking pod dependency because it has UIWebview Control, so apple will no accept App with UIWebview, I suggest you to replace AFNetworking with Alamofire's latest version pod
![Screenshot 2020-02-24 at 6 53 03 PM](https://user-images.githubusercontent.com/49636415/75155845-e597c200-5736-11ea-85a4-b24cae68c063.png)

**Comment by cogtea** [comment]
@DangarOpenxcell Please check the following issue https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by DangarOpenxcell** [comment]
> @DangarOpenxcell Please check the following issue [AFNetworking/AFNetworking#4428](https://github.com/AFNetworking/AFNetworking/issues/4428)
