### ISSUE TITLE
SDK integration issue in application

### ISSUE THREAD

**Issue by Hamza123Imran** [paytabscom/paytabs-ios-library-sample#18]
Hi, I have tried to follow your provided SDK integration document but I'm facing some issues while doing all the processes. I have drag and drop both `Resources.bundle` and `paytabs-iOS.framework` into my project. After that, I have updated info.plist file and added `#import <paytabs-iOS/paytabs_iOS.h>` header file in my Bridging header class also i have change the Other Linker Flag as mentioned in the document. Now when I clean and build the project it shows me error of Pods file not found. I have installed all the pod files mentioned in the document and when i try to run the application it shows me error message of `Pod file not found`. 
Why is it so, i have followed each n every steps as mentioned in the document. What am i missing in that?
![PHOTO-2020-04-16-20-42-27](https://user-images.githubusercontent.com/26136054/79752418-b6b05d80-832d-11ea-8938-cb9add941753.jpg)
![PHOTO-2020-04-17-09-53-35 2](https://user-images.githubusercontent.com/26136054/79752430-badc7b00-832d-11ea-8717-25d47c9c1236.jpg)
![PHOTO-2020-04-17-09-53-35](https://user-images.githubusercontent.com/26136054/79752434-bc0da800-832d-11ea-899d-b0fd91b198b2.jpg)
These are the errors i'm facing. Please help me in that.

**Comment by cogtea** [comment]
@Hamza123Imran In case if you are using OCR version, please add the following dependency
``` 
pod 'PayCardsRecognizer'
```

**Comment by Hamza123Imran** [comment]
I have tried with OCR and without OCR by commenting the OCR pod file. But whenever i try to do all setup as mention in document, i face an error that `Pod file not found`

**Comment by Walid-033** [comment]
Hi hamza, please try our samples available on github with your account (merchant id & secret key).
if the error still appears, please produce the issue with a sample app and forward the sample to us with same results, logs, dependencies and third party libraries

**Comment by Walid-033** [comment]
and provide the below information for further investigations,,,,
environment (Xcode version,device IOS version etc), and which programing (Swift, Java, etc)

**Comment by aalisher5** [comment]
HI @Walid-033 the xcode version is Version 11.3.1 (11C504), Device is Iphone 11 Max Pro

**Comment by aalisher5** [comment]
@Walid-033 there might be no issue with your sample application, that is not our issue at all, the issue is when we integrate the Paytabs SDK in our application its not getting integrated, and i have explained the issue in detail email.
My initial assumption is its due to conflicting dependencies i.e. Reachability , IQKeyboardManager , ReachabilitySwift, IQKeyboardManagerSwift.
1: When we exclude ReachabilitySwift, IQKeyboardManagerSwift in pod file our project wouldn't run.
2: IF we exclude Reachability , IQKeyboardManager  Paytabs Sdk gives error missing header files. 
3: When we include both we get this error.
<img width="245" alt="Screenshot 2020-04-21 19 21 33" src="https://user-images.githubusercontent.com/6779477/79877158-5391fa00-8405-11ea-98ad-e9abffe3044f.png">

**Comment by Hamza123Imran** [comment]
> Hi hamza, please try our samples available on github with your account (merchant id & secret key).
> if the error still appears, please produce the issue with a sample app and forward the sample to us with same results, logs, dependencies and third party libraries

I can use it, if my error get remove. First issue i'm facing is regarding pod file not found.
I have integrated SDK in both existing project and new project but face same errors.

**Comment by cogtea** [comment]
@Hamza123Imran  You can't exclude our dependencies, otherwise SDK will not work, you are using same dependencies with swift flavor,

**Comment by cogtea** [comment]
@Hamza123Imran You can't exclude the SDK dependencies, and you are using same dependency but with Swift flavor, for example https://github.com/tonymillion/Reachability, it is required by the SDK, also it supporting Swift, so you can remove `ReachabilitySwift` and modify your app to fit `Reachability`, it should fix your conflict.

**Comment by cogtea** [comment]
Please use the latest version `4.0.8` https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk

**Comment by Ashish23451** [comment]
Hello team

i integrated successfully apple pay with paytabs payment gateway but i have a error
Response Code: 4001

Response Result: The request is not properly formatted.

Tokenization Cutomer Email: 

Tokenization Customer Password: 

TOkenization Token: 

please help us as soon as possible

Thanks
Ashish

**Comment by Priyali-hub** [comment]
I am trying to pay with paytabs I am using paytabs v4.0.8-lite(ios) version but when I click on pay button nothing happens.i am using simulator 8(13.3)  and xcode 11.3

Please help
