### ISSUE TITLE
Error: invalid expiry date

### ISSUE THREAD

**Issue by hesham91fci** [paytabscom/paytabs-ios-library-sample#19]
Currently I can open PTFWInitialSetupViewController successfully but when I press on the button pay now it alerts me a message of invalid expiry date, although I'm specifying them, I've tried various versions 4.0.6,4.0.1 and finally now I'm on 4.0.7 all of them having the same result, kindly find screenshot for my simulator, any thoughts of what am I missing

<img width="720" alt="Screen Shot 2020-04-21 at 5 47 00 PM" src="https://user-images.githubusercontent.com/4971507/79889131-e3cc4100-83fd-11ea-86df-1e800b9c9130.png">

Best regards

**Comment by cogtea** [comment]
@hesham91fci month 01 , year 20, is invalid expiry date.
