### ISSUE TITLE
Screen freezes in iOS 13 after dismissing paytab screen on drag to dismiss

### ISSUE THREAD

**Issue by binal-hiddenbrains** [paytabscom/paytabs-ios-library-sample#2]
Application freezes when I dismiss a paytab controller on dragging down to dismiss in iOS 13. 
Please run this sample application in iPhoneX iOS 13. and check the screen shots.

![Simulator Screen Shot - iPhone X - 2019-11-05 at 10 53 51](https://user-images.githubusercontent.com/38208004/68180724-ba883780-ffba-11e9-9f4a-0ae2426215df.png)
![Simulator Screen Shot - iPhone X - 2019-11-05 at 10 53 57](https://user-images.githubusercontent.com/38208004/68180725-ba883780-ffba-11e9-84b6-8448bf3f87d4.png)

**Comment by alpbak** [comment]
Have you found any solutions?

**Comment by Ahmed-Masoud** [comment]
any solutions yet ?

**Comment by cogtea** [comment]
@alpbak  @Ahmed-Masoud @binal-hiddenbrains  We just updated the repo with a new version for SDK **v4.0.3**, and we disabled presentationModel behaviour with IOS 13, please update your app and let us know if you still have any issue.

SDKs: https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk

**Comment by Ahmed-Masoud** [comment]
@cogtea the present issue is fixed but the expiry date pickers doesn't show when clicked

**Comment by cogtea** [comment]
@Ahmed-Masoud Can you please mention the IOS version, and which SDK version?

**Comment by Ahmed-Masoud** [comment]
ios 13 SDK 4.0.3
prior ios 13 is working fine

**Comment by cogtea** [comment]
@Ahmed-Masoud Are you using `ActionSheetStringPicker` in your app? can you please run the sample with update SDK 4.0.3?

**Comment by Ahmed-Masoud** [comment]
no am not using this pod

**Comment by alpbak** [comment]
I tested the SDK v4.0.3. Swipe down to dismiss is disabled and the problem is solved. Thanks

**Comment by cogtea** [comment]
> no am not using this pod

Please try the sample with the latest SDKv4.0.3

**Comment by paytabscom** [comment]
Hi Ahmed our latest SDK v4.0.4 has the fix for this issue now, please check it and let us know your feedback. Thanks
