### ISSUE TITLE
crash when calling this line ==>   initialSetupViewController.didMove(toParentViewController: self);

### ISSUE THREAD

**Issue by sarakhater** [paytabscom/paytabs-ios-library-sample#21]
when calling this line ==>   initialSetupViewController.didMove(toParentViewController: self);

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PTFWHTTPSessionManager POST:parameters:constructingBodyWithBlock:progress:success:failure:]: unrecognized selector sent to instance 0x600001081c20'

**Comment by cogtea** [comment]
@sarakhater Please check this issue https://github.com/paytabscom/paytabs-ios-library-sample/issues/17

**Comment by raeesdoduae** [comment]
I am still facing the same issue, please suggest a solution, I am stuck for long time

**Comment by cogtea** [comment]
@raeesdoduae Please use the latest version `4.0.8` https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk

**Comment by raeesdoduae** [comment]
@cogtea i am using SDK v4.0.8 Lite version, still have the issue

**Comment by cogtea** [comment]
You need to install latest version of AFnetwork 4.0.1, and clean project build folder.

**Comment by raeesdoduae** [comment]
![image](https://user-images.githubusercontent.com/66007713/83015288-42a25d00-a031-11ea-943a-858765d9c185.png)
yes, I am using AFNetworking 4.0.1, I didn't understand whats wrong

**Comment by raeesdoduae** [comment]
Fixed it thanks :)
