### ISSUE TITLE
payment page

### ISSUE THREAD

**Issue by najdi77** [paytabscom/paytabs-ios-library-sample#22]
[PTFWHTTPSessionManager POST:parameters:constructingBodyWithBlock:progress:success:failure:]: unrecognized selector sent to instance 0x600002756670

I'm still getting this error and I can't view payment page

**Comment by cogtea** [comment]
Please use the latest version `4.0.8` https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk
