### ISSUE TITLE
iOS 13 full screen present not working , How to disable swipe down gesture 

### ISSUE THREAD

**Issue by DangarOpenxcell** [paytabscom/paytabs-ios-library-sample#3]
How to disable swipe down gesture

**Comment by DangarOpenxcell** [comment]
Hello, 

We are implementing the payment integration in Android/iOS with your PayTabs mobile SDK into one of our app.

As we try with the test cards information and we found that the card "without authentication" is worked only with "USD" and "SAR" currency but not working with "EGP" and getting technical error message with response code : 800. 

So may I know how to make successful transactions with "EGP" (Egypt)?.

Thank you

**Comment by Ahmed-Masoud** [comment]
did you find any solution for presentation problem ?

**Comment by cogtea** [comment]
@Ahmed-Masoud  @DangarOpenxcell Instead of using (As per example)
```swift
self.view.addSubview(initialSetupViewController.view)
self.addChildViewController(initialSetupViewController)
initialSetupViewController.didMove(toParentViewController: self)
```

You can use 
```swift
self.modalPresentationStyle = .fullScreen
self.present(self.initialSetupViewController, animated: false)
```

Please check https://stackoverflow.com/a/56435511

**Comment by Ahmed-Masoud** [comment]
This is not working tried it before the reason is (and i am guessing since it’s a closed source) that they are using container view controllers and children components actually the problem is with the creditcardview which is on top of initial vc even if you tried the vc that presented the initial sdk vc will disparate magically 😅
Anyways i used the rest api instead of sdk and is working perfectly

**Comment by cogtea** [comment]
@Ahmed-Masoud We are working on fixing this issue, will back to you soon.

**Comment by cogtea** [comment]
@Ahmed-Masoud @DangarOpenxcell we disabled presentationModel behaviour with IOS 13, please update SDK to v4.0.2
[ios_sdk-v4.0.2-lite.zip](https://github.com/paytabscom/paytabs-ios-library-sample/files/4012620/ios_sdk-v4.0.2-lite.zip)

**Comment by DangarOpenxcell** [comment]
Thank for support
