### ISSUE TITLE
WebView depreciated which is used in AfNetworking referenced by PayTab lib

### ISSUE THREAD

**Issue by avaan** [paytabscom/paytabs-ios-library-sample#4]
Hi,

When i submit my app to Apple app store it got rejected with below error,

Bug: ITMS-90809: Deprecated API Usage - UIWebView

when I search my code for UIWebView its been found in AfNetworking, this framework is used in PayTab IOS version.

Please let me know how to fix it.

**Comment by parveenBanuS** [comment]
Hi are u using this lib in which xcode?

**Comment by cogtea** [comment]
@parveenBanuS @avaan  We just updated the repo with a new version for SDK **v4.0.3**, we replaced `UIWebView` with `WKWebView`, please update your app and let us know if you still have any issue.

SDKs: https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk
