### ISSUE TITLE
Paytabs crash in xcode 10.3

### ISSUE THREAD

**Issue by parveenBanuS** [paytabscom/paytabs-ios-library-sample#5]
Paytabs is crash i tried the same demo app in personal demo project but it was crash

Reason:
"DemoPayment[1280:20944] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString isValidAddressString]: unrecognized selector sent to instance 0x91033b72b73182f7'
*** First throw call stack:"

PTFWInitialSetupViewController
![Screenshot 2019-11-23 at 10 09 59 AM](https://user-images.githubusercontent.com/40426461/69473348-74fca480-0dd9-11ea-915a-bed62dde5f84.png)

**Comment by parveenBanuS** [comment]
when i added the secret key it was crash...

**Comment by alpbak** [comment]
Any solutions for this? I get the same error.

**Comment by parveenBanuS** [comment]
> Any solutions for this? I get the same error.

You just follow the steps its working i think you missed -all_load   -ObjC add this lib.

**Comment by alpbak** [comment]
> > Any solutions for this? I get the same error.
> 
> You just follow the steps its working i think you missed -all_load -ObjC add this lib.

Yes, that was the case. Thanks
