### ISSUE TITLE
Getting Error "Request must be in Json format with content type application/json" when paying amount

### ISSUE THREAD

**Issue by ParvendraSingh** [paytabscom/paytabs-ios-library-sample#51]
I have implemented the latest version (6.0.10-beta), When i enter test card details and click on pay, i am getting an error **"Request must be in Json format with content type application/json"**

I am getting this same error on Android and iOS both plateform.

Please suggest what should i have to do.  @MuhamedAdly @paytabscom 

![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 15 41 18](https://user-images.githubusercontent.com/7079396/113128599-996f5900-9237-11eb-8c15-b3e8b5e47eff.png)

**Comment by ParvendraSingh** [comment]
we can only solve this problem by communicate with Paytabs support.
They can only solve this issue for your Paytabs Account

**Comment by sunnysannii1** [comment]
my merchant account is created at https://www.paytabs.com/login/ PT v1  how can I use pt 1 iOS sdk can you name version?

**Comment by ParvendraSingh** [comment]
@sunnysannii1 
Please contact to Paytabs support they update some settings on paytabs account for Mobile SDK.
You need to contact support.
