### ISSUE TITLE
Request must be in JSON Format

### ISSUE THREAD

**Issue by sunnysannii1** [paytabscom/paytabs-ios-library-sample#53]
pod 'PayTabsSDK', '~> 6.0.17' ![Simulator Screen Shot - iPhone 11 Pro - 2021-04-15 at 10 53 53](https://user-images.githubusercontent.com/26668177/114820959-47066e80-9dd9-11eb-9756-d9ecdb62970a.png)  
added this pod facing issue after adding details

**Comment by MuhamedAdly** [comment]
It seems you are using the web keys, you should use Mobile SDK keys, please contact customer support to generate the required key.

**Comment by sunnysannii1** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-04-16 at 10 10 18](https://user-images.githubusercontent.com/26668177/114974511-f3a92480-9e9b-11eb-83a9-ac2ab7591e27.png)
after using mobile sdk keys
