### ISSUE TITLE
When I Try to transaction at that time "Payment not Complete issue"

### ISSUE THREAD

**Issue by ankitinception** [paytabscom/paytabs-ios-library-sample#56]
Hello,

I have configuration below details and we don't have cart functionality for project so as a cart id we are passing timestamp.

configuration = PaymentSDKConfiguration(profileID: "478**",
serverKey: "SHJNLLN2L6-HZKMK2MRGZ-****************",
clientKey: "C2KMDM-2D6BH9-KNKMNR-T2*****",
cartID: "\(currentTimeStamp ?? 123321)",
currency: "AED",
amount: 1.0,
merchantName: "Dooby Doo FZ LLC",
cartDescription: "Dooby",
merchantCountryCode: "ae", // ISO alpha 2
merchantIdentifier: "merchant.com.dooby.user",
paymentNetworks: nil,
forceShippingInfo: false)

![119142525-3e522980-ba64-11eb-8527-b07db0d59cb4](https://user-images.githubusercontent.com/53896908/119326002-17336c00-bc9f-11eb-86d1-7895264a33f5.jpg)

Please help me on this.

**Comment by MuhamedAdly** [comment]
Make sure you are using the correct mobile SDK keys not the server-to-server keys, you can get them from the dashboard/developer section.
