### ISSUE TITLE
Save Card instead of asking user again and Again

### ISSUE THREAD

**Issue by sunnysannii1** [paytabscom/paytabs-ios-library-sample#57]
is there any option in SDK where user can save card in Pay tab sdk and just select when to use instead of adding again

**Comment by MuhamedAdly** [comment]
you can use the tokenization feature, you can enable tokenization by setting the parameter of tokeniseType with your prefered type and will receive a token & transaction ref in the first successful transaction, you will save them and pass them again in the configuration for the next payments.

you can find more details here: https://github.com/paytabscom/paytabs-ios-library-sample#tokenisation

**Comment by sunnysannii1** [comment]
I Tried with token and reference and save the Card but when begin to pay next it say Unable to Process your request 

[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}

**Comment by sunnysannii1** [comment]
func paymentManager(didRecieveValidation error: Error?) {
        print(error?.localizedDescription ?? "")
    }

it returns "Unable to process your request" after I passed reference and token in configuration

**Comment by sunnysannii1** [comment]
Token: 2C4651BF67A3EC33C6B691F9678678B1
Transaction Reference: TST2116000194301
here is items

**Comment by MuhamedAdly** [comment]
Please send a request to enable tokenization to the support team at cs@paytarbs.com.
