### ISSUE TITLE
Store last 4 digit of card number

### ISSUE THREAD

**Issue by Jignya-vc** [paytabscom/paytabs-ios-library-sample#59]
Is there any option from where i can store last 4 digit of card number ?

**Comment by MuhamedAdly** [comment]
Yes you can get a masked card number after the payment completed in the delegate "didFinishTransaction" you will receive an object of payment transaction details , it contains many details and their you will find the masked card number and network name.

**Comment by Jignya-vc** [comment]
I have checked but not find property for masked card number. if possible can you share example ?

**Comment by MuhamedAdly** [comment]
You can find it inside the sub object paymentInfo

cardType, schema, paymentDescription

**Comment by MuhamedAdly** [comment]
For security we don't pass the expiry date in the callbacks

**Comment by Jignya-vc** [comment]
> You can find it inside the sub object paymentInfo
> 
> cardType, schema, paymentDescription

working for me.
Thanks

**Comment by Jignya-vc** [comment]
Hello ,


I need to store card details for future use. I am doing it with locally store information transaction reference number and token.

I found from the doc to pass stored transaction reference number and token while paying with saved card. but it is showing me error "payment not processed" . Can you please let me know if i forgot something

Is there pay tabs default feature to save and retrieve card details ?


Thanks,
________________________________
