### ISSUE TITLE
Archive issue in Paytabs frame work:

### ISSUE THREAD

**Issue by parveenBanuS** [paytabscom/paytabs-ios-library-sample#6]
All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/vividinfotech/Desktop/new/InviteGamers/InviteGamers/paytabs-iOS.framework/paytabs-iOS' for architecture arm64

**Comment by salahamassi** [comment]
any new news?

**Comment by cogtea** [comment]
@parveenBanuS  @salahamassi We are working on new SDK release, migrating `UIWebView` to `Wkwebview`

Will update soon!

**Comment by parveenBanuS** [comment]
working fine
