### ISSUE TITLE
Store card information does not work 

### ISSUE THREAD

**Issue by Jignya-vc** [paytabscom/paytabs-ios-library-sample#60]
I need to store card details for future use. I am doing it with locally store information transaction reference number and token.

i found from the doc to pass stored transaction reference number and token while paying with saved card. but it is showing me error "payment not processed" . Can you please let me know if i forgot something

Is there paytabs default feature to save and retrieve card details ?

**Comment by MuhamedAdly** [comment]
It should be enabled by the our technical support team, please send a request to enable the tokenization & recurring to the support team at cs@paytarbs.com.

**Comment by Jignya-vc** [comment]
Hello ,


What I need to share with you.  I didn't get it.

we have multiple users in future who will use this feature. so how it can be managed ?


Thanks,
Jignya
________________________________

**Comment by MuhamedAdly** [comment]
First you should store the transaction reference and token after the first normal payment using the card, after that you pass the token and transaction reference saved earlier into the configuration, this will make the payment without showing card input view again.

**Comment by Jignya-vc** [comment]
yes
I have done the same but is showing payment process error while doing payment with stored card.
________________________________

**Comment by MuhamedAdly** [comment]
It should be activated by our support team to be able to do it, send an email and will activate tokenization and recurring for you.

**Comment by Jignya-vc** [comment]
Okay.
I got it

But I have concern regarding in real time, when customer will use this feature then it is not possible to send tokenization.

What is the resolution for it ? In that case how to activate.
________________________________

**Comment by MuhamedAdly** [comment]
Every customer has a separate token for every card he pay with.

**Comment by MuhamedAdly** [comment]
You are activating your account on PayTabs to have the tokenization feature enable.

**Comment by Jignya-vc** [comment]
Okay.

Does Paytabs provide save card/ retrieve card  feature ?
________________________________

**Comment by MuhamedAdly** [comment]
We don't have an API to save cards or retrieve cards? the cards are automatically saved in our servers after each payment transaction.

**Comment by Jignya-vc** [comment]
Okay

Thanks for the support.

Last question :

From where I can enable tokenization feature ?.
 In merchant site I can't see any setting for this option.
________________________________

**Comment by MuhamedAdly** [comment]
Only the activation team can enable it, Please contact them on cs@paytabs.com.

**Comment by Jignya-vc** [comment]
Okay

Thanks
________________________________
