### ISSUE TITLE
Request must be in JSON format 

### ISSUE THREAD

**Issue by raeesdoduae** [paytabscom/paytabs-ios-library-sample#63]
I'am getting error saying that, "Request must be in JSON format with content type application/json"

Showing in **Test mode**
**'PayTabsSDK', '~> 6.1.2'**

![Simulator Screen Shot - iPhone 12 mini - 2021-08-09 at 10 17 47](https://user-images.githubusercontent.com/66007713/128668993-8a4143d5-928f-4744-887d-50fdba7acb90.png)

**Comment by MuhamedAdly** [comment]
Make sure you're using the correct mobile SDK keys not the server to server keys.

**Comment by raeesdoduae** [comment]
How I will get separate key for mobile SDK,Please give me solution

**Comment by raeesdoduae** [comment]
Send an email to Customercare@paytabs.com to get your Mobile SDK keys
