### ISSUE TITLE
I'm using swift 4.2 and I can't get rid of this error " linker command failed with exit code 1"

### ISSUE THREAD

**Issue by HyperDesignIOS** [paytabscom/paytabs-ios-library-sample#7]
Undefined symbols for architecture x86_64:
  "_PKPaymentNetworkMada", referenced from:
      -[PTFWInitialSetupViewController handleMerchantInfoFetchResponseEvent:] in paytabs-iOS(PTFWInitialSetupViewController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cogtea** [comment]
@HyperDesignIOS Please mention which IOS version?

**Comment by HyperDesignIOS** [comment]
this is Xcode Version 10.1 (10B61)

**Comment by paytabscom** [comment]
Hi @HyperDesignIOS we have recently released a new IOS SDK v 4.0.4 can you please check and let us know if you are still facing the same issues?
