### ISSUE TITLE
Done Button not visible on Card Date

### ISSUE THREAD

**Issue by fbihack** [paytabscom/paytabs-ios-library-sample#8]
As you can see on the screenshots provided below, the "Done" and "Cancel" actions aren't shown as they are white instead of black.
Is there a way to set this color?
When will this issue be fixed?
Many thanks in advance

![screen1](https://user-images.githubusercontent.com/457688/71619665-cca2e280-2bc5-11ea-9198-0def2c5a2684.jpg)
![screen2](https://user-images.githubusercontent.com/457688/71619666-cca2e280-2bc5-11ea-9b9f-38be94c3a475.PNG)

**Comment by cogtea** [comment]
@fbihack  Unfortunately the SDK doesn't have color option for these buttons, but we just updated the repo with a new version for SDK **v4.0.3**, and we made these button consistent with other action button, same color (Black), please update your app and let us know if you still have any issue.

SDKs: https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk

**Comment by fbihack** [comment]
Dear @cogtea many thanks!
It works perfectly. It’s probably that the issue could also be releated to the fact that the ui text color of the parent frame was white.
Anyway it works nicely now.
Thanks again for the great support
