### ISSUE TITLE
[!] No podspec exists at path `/Users/ruman/.cocoapods/repos/trunk/Specs/b/5/f/PayTabsSDK/6.4.6/PayTabsSDK.podspec.json`.

### ISSUE THREAD

**Issue by rumanEntcco** [paytabscom/paytabs-ios-library-sample#84]
when i am running pod install i am getting this error

[!] No podspec exists at path `/Users/ruman/.cocoapods/repos/trunk/Specs/b/5/f/PayTabsSDK/6.4.6/PayTabsSDK.podspec.json`.

**Comment by MuhamedAdly** [comment]
please update your pod to the latest version.
