### ISSUE TITLE
Freeze and crash in latest version

### ISSUE THREAD

**Issue by Amin-0-1** [paytabscom/paytabs-ios-library-sample#87]
PayWithCard Screen freeze on interaction whatever it is , specially when trying to cancel or back from the screen or just press pay now button, it freeze the entire app and after a while it crashes , it gives this in the debugging area 
```
assertion failed [thread_context != nullptr]: got an exception for an unknown thread
(ExceptionServer.cpp:505 handle_exception)
 ```

**Comment by maulikm235** [comment]
> PayWithCard Screen freeze on interaction whatever it is , specially when trying to cancel or back from the screen or just press pay now button, it freeze the entire app and after a while it crashes , it gives this in the debugging area
> 
> ```
> assertion failed [thread_context != nullptr]: got an exception for an unknown thread
> (ExceptionServer.cpp:505 handle_exception)
> ```

I have same issue so i am using pod **'PayTabsSDK', '~> 6.5.0'**, it will work for you, 
i don't know why the developers are not solving this issue.

**Comment by amr-Magdy-PT** [comment]
Hello,  please contact the [support team ](mailto:cs@paytabs.com) to collect the necessary data for this issue and will be solved ASAP.
