### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by abdalazemSaleh** [paytabscom/paytabs-ios-library-sample#88]
checksum of downloaded artifact of binary target 'PaymentSDK' (ef7db5957857b1994a510b59ef7255f6fd7785feb844d63f06b99d98487229c6) does not match checksum specified by the manifest (d806c13944dade2d465aa2232679083efaa2d90e50a1581b4cb0bc0f5ef91e8c)

**Comment by burhanuddin353** [comment]
Getting the same error.

**Comment by Rj707** [comment]
checksum of downloaded artifact of binary target 'PaymentSDK' (da660bc2913d03012ec88eaf3d19980883f1c2562975bc3d5f8582a31036bf35) does not match checksum specified by the manifest (d806c13944dade2d465aa2232679083efaa2d90e50a1581b4cb0bc0f5ef91e8c) 
@humayun-paytabs @paytabscom @AdlyPayTabs

**Comment by Rj707** [comment]
@abdalazemSaleh @burhanuddin353 did you guys find any solution?

**Comment by Rj707** [comment]
> ```
> dependencies: [
>     .package(url: "https://github.com/paytabscom/paytabs-ios-library-sample.git", .upToNextMajor(from: "6.6.21"))
> ]
> ```
> 
> checksum of downloaded artifact of binary target 'PaymentSDK' (da660bc2913d03012ec88eaf3d19980883f1c2562975bc3d5f8582a31036bf35) does not match checksum specified by the manifest (d806c13944dade2d465aa2232679083efaa2d90e50a1581b4cb0bc0f5ef91e8c) @humayun-paytabs @paytabscom @AdlyPayTabs

Even if I try to simply use it as a package inside my xcode project using SPM, I am facing warnings
<img width="646" alt="Screenshot 2024-10-08 at 9 42 41 AM" src="https://github.com/user-attachments/assets/32c2017f-f857-46c3-a93c-23db271d36d8">

**Comment by MuhamedAdly** [comment]
please check the latest version 6.6.2

**Comment by Rj707** [comment]
> please check the latest version 6.6.2, the checksum updated.

I'll look into it. Could you please update the README.md accordingly? Thanks! 
@MuhamedAdly

**Comment by Rj707** [comment]
> > please check the latest version 6.6.2, the checksum updated.
> 
> I'll look into it. Could you please update the README.md accordingly? Thanks! @MuhamedAdly

@MuhamedAdly I am still facing the issue.

<img width="1508" alt="Screenshot 2024-10-08 at 9 33 00 PM" src="https://github.com/user-attachments/assets/ad2b22b0-336a-4cc2-b027-3675220f79e0">

**Comment by Rj707** [comment]
@MuhamedAdly @paytabscom @humayun-paytabs

**Comment by MuhamedAdly** [comment]
Remove the old SPM, add it again using the GitHub link, and set the exact version 6.6.22.

<img width="842" alt="image" src="https://github.com/user-attachments/assets/d4099e5a-844a-4f05-9d67-f9ee398a0178">
