### ISSUE TITLE
Apple will not accept app with use UIWebview Control

### ISSUE THREAD

**Issue by DangarOpenxcell** [paytabscom/paytabs-ios-library-sample#9]
hi..

PayTab use AfNetworking library and it will use UIWebView internally so apple will not accept app on the app store so please change dependancy pod-like AfNetworking to Alamofire and make sure other dependancy will not use internally any UIwebview control 

![Screenshot 2020-01-01 at 11 28 31 AM](https://user-images.githubusercontent.com/49636415/71638762-86658600-2c8e-11ea-914b-2ead939b040f.png)

**Comment by cogtea** [comment]
@DangarOpenxcell  Thanks for your issue, actually we are using UIWebView for 3d secure pages redirection, and we are planing to replace with WKWebView.

For AfNetworking library, we can avoid by using subspecs https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by cogtea** [comment]
@DangarOpenxcell We just updated the repo with a new version for SDK v4.0.3, we replaced `UIWebView` with `WKWebView`, please update your app and let us know if you still have any issue.

SDKs: https://github.com/paytabscom/paytabs-ios-library-sample/tree/master/sdk
